name: CI

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_IMAGE_NAME }}"  # Use secret for image name
        IMAGE_TAG="v$(date +%Y%m%d%H%M%S)"  # Tag with current timestamp
        docker build -t $IMAGE_NAME:$IMAGE_TAG .

    - name: Push Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_IMAGE_NAME }}"
        IMAGE_TAG="v$(date +%Y%m%d%H%M%S)"
        docker push $IMAGE_NAME:$IMAGE_TAG
